// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (C) 2023, Advanced Micro Devices, Inc.
 */

#ifndef __KSB_CSI_REG_H
#define __KSB_CSI_REG_H

#define CSI_UPORT_OFFSET 0x100000
#define CSI_EXERCISER_OFFSET 0x300000

/*CSI Exerciser*/
#define CSI_NPR_DEST_ID 0x0
#define CSI_CMPL_DEST_ID 0x4
#define CSI_PR_DEST_ID 0x8
#define CSI_NPR_CREDIT 0xC
#define CSI_CMPL_CREDIT 0x10
#define CSI_PR_CREDIT 0x14
#define CSI_BUF_ID_SOURCE2 0x1C
#define CSI_TXN_STATUS 0x24
#define CSI_CTRL 0x28
#define CSI_CMPL_DEST_FIFO_ID_SOURCE1 0x2C
#define CSI_CMPL_DEST_FIFO_ID_SOURCE2 0x30
#define CSI_INPUT_SOURCE1 0x34
#define CSI_INPUT_SOURCE2 0x38
#define CSI_INIT_CREDITS_SOURCE2 0x44

#define CSI_UPORT_DST_ID_BASE 0x8
#define CSI_CTRL_RESET_COUNTERS 0x300
#define CSI_CTRL_LOAD_CREDITS 0x38
#define CSI_CTRL_INITIATE_CMPL 0x2
#define CSI_CTRL_CLEAR 0x0
#define CSI_UPORT_CMPL_DEST_FIFO_ID 0x0
#define CSI_UPORT_CMPL_CREDITS 0x118
#define CSI_EXER_INPUT_SOURCE_PCIE0 0x4
#define CSI_EXER_INPUT_SOURCE_PSX 0xC

#endif
